### ISSUE TITLE
Download listing showing on Cart Widget

### ISSUE THREAD

**Issue by cklosowski** [SDavisMedia/vendd#14]
The list of downloads on an empty cart that show on the checkout screen is also showing on the cart widget when it's empty

![image](https://cloud.githubusercontent.com/assets/1390124/7666507/ffd6763e-fb9c-11e4-89d8-82d5ec58966c.png)

**Comment by SDavisMedia** [comment]
@cklosowski I fixed that pretty late last night. It should be in master already (as if there was another branch :stuck_out_tongue:).

**Comment by cklosowski** [comment]
Interesting. I pulled down master. Forget to push?

**Comment by SDavisMedia** [comment]
Nope it should all be current. Here's the CSS: https://github.com/SDavisMedia/vendd/blob/master/style.css#L1765

**Comment by cklosowski** [comment]
Ah, caching...we should see if we can make that not even run though. Since CSS just hides it, the database is still running against it, which is unnecessary. I'll see if I can figure this out.

**Comment by SDavisMedia** [comment]
I was going to say that but didn't because I couldn't figure out how it'd work off the top of my head. If we can do it, that'd be great. I don't want it to depend on the use of the page template itself, though. It should work anywhere the checkout shortcode is used.

**Comment by cklosowski** [comment]
@SDavisMedia how's this look?

**Comment by SDavisMedia** [comment]
You da man! I'm about to take off or I'd make an adjustment myself, but you think we can broaden the scope of the single/page/checkout conditional so that no matter what, the cart widget displays "Your cart is empty." but the checkout page shows all the goodies when empty? I say that because there's a Customizer option for the empty cart page title and that's actually what's showing in the widget when empty. So if the user changes that title and it's in the context of actually being on the empty cart page, the widget could end up showing something like "Your cart is empty! Look below to..." you know?

Plane rolling down the runway. Back in a bit!

**Comment by SDavisMedia** [comment]
@cklosowski @mindctrl have a look at the changes I made when you get a chance. https://github.com/SDavisMedia/vendd/commit/459b2ef316a1e31b47410f09f88b62db07dab01d

All good from my end. I'll merge if you guys agree.

**Comment by SDavisMedia** [comment]
Gonna go ahead and merge that. :+1:
